
\section{Examples}

\begin{frame}[fragile]{Data preparation}
<<>>=
## options
options(stringsAsFactors=FALSE)
options(warn=-1) # don't warn missing values
Sys.setlocale("LC_TIME","C")

## libraries
library(dplyr)
library(ggplot2)
theme_set(theme_bw()) # just my preference
library(reshape2)
library(chron)
options(chron.year.abb=FALSE)

## functions
source("grb001.R")
source("functions.R")

## input
data = read.table("data/2014/LAU.csv",sep=";",skip=6,
  col.names=c("datetime","O3","NO2","CO","PM10","TEMP","PREC","RAD"))

## date/time conversions
data = Addtimes(data)

## pivot to long format
lf = melt(data,id.vars=c("datetime","year","day","month","hour","wkday","wkend"))
@ 

\end{frame}


\begin{frame}[fragile]
  \frametitle{Ozone in Lausanne (ECDF)}
  
  \begin{columns}[b]
    \column{.5\textwidth}  

We will first view ECDFs of hourly concentrations for 2013.
<<>>=
ggp = ggplot(data)+
  stat_ecdf(aes(x=O3),geom="line")+
  xlab(expression("O3 concentration"~(mu*g/m^3)))+
  ylab("Probability")
@ 

<<echo=FALSE,dev='png',fig.width=7,fig.height=5>>=
print(ggp)
@ 
\column{.5\textwidth}

We can also segregate the ECDFs by month; for ozone there is a particularly strong variation.
<<>>=
ggp = ggplot(data)+
  stat_ecdf(aes(x=O3,group=month,color=month),
            position="identity",
            geom="line")+
  xlab(expression("O3 concentration"~(mu*g/m^3)))+  
  ylab("Probability")
@ 

<<echo=FALSE,fig.width=7,fig.height=5>>=
print(ggp)
@ 

\end{columns}
\end{frame}

\begin{frame}[fragile]
  \frametitle{Ozone in Lausanne (probability/kernel density)}  
  \begin{columns}[b]
    \column{.5\textwidth}  
    
The annual probability density appears to be multimodal, but we can see that this is due to the strong variation in seasonal probability distributions of ozone concentrations.
<<>>=
ggp = ggplot(data)+
  stat_density(aes(x=O3,ymax=..density..),
               position="identity",
               geom="line")+
  xlab(expression("O3 concentration"~(mu*g/m^3)))  
@ 

<<echo=FALSE,fig.width=7,fig.height=5>>=
print(ggp)
@ 

\column{.5\textwidth}

<<>>=
ggp <- ggplot(data)+
  stat_density(aes(x=O3,ymax=..density..,
                   group=month,color=month),
               position="identity",
               geom="line")+
  xlab(expression("O3 concentration"~(mu*g/m^3)))  
@ 

<<echo=FALSE,fig.width=7,fig.height=5>>=
print(ggp)
@ 

\end{columns}
\end{frame}

\begin{frame}[fragile]{All pollutants in Lausanne, 2014}
  
<<>>=
pollutants = lf %>% filter(variable %in% c("CO","O3","NO2","SO2","PM10"))
ggp = ggplot(pollutants)+
  stat_ecdf(aes(x=value,group=month,color=month),
            position="identity",
            geom="line")+
  facet_grid(.~variable,scale="free_x")+
  xlab("Value")+  
  ylab("Probability")
@   

<<echo=FALSE,fig.width=10,fig.height=3.5>>=
print(ggp)
@ 
  
  
\end{frame}

\end{document}



